### ISSUE TITLE
client.js - createChannel() method

### ISSUE THREAD

**Issue by crookse** [drashland/sockets#24]
Add `createChannel()` to client.js. The `createChannel()` method will send a message to the server saying it wants to create a channel. The server will then create a channel.

Acceptance Critera
* client.js `createChannel()` exists
* `SocketServer` has a reserved event (`create_channel`) that creates a channel

**Comment by saragee3** [comment]
Closing this. We can revisit these issues in https://github.com/drashland/sockets-client if needed.
