### ISSUE TITLE
Video Tutorial - General

### ISSUE THREAD

**Issue by ebebbington** [drashland/sockets#49]
## Summary

What: Video tutorial (acts of visual documentation) for how to use Sockets, and how it works on certain level. For example, one video could be made on basic usage, then others could be made on the 'advanced stuff' ie "How to create a multilayer room that signals 500 times a second to 10,000 clients, whilst polls the database..." - you get the jist i hope :) Though it's open to whoever takes on this issue how they'd like to do the video and what content it will have.

Could be useful to include in the description of the video, times of topics, eg:

0:00 - introduction
0:23 - what is sockets
5:10 - creating rooms

Why: Supports visual learners, and thus creates another platform for people to understand Sockets and how to use it - further enforcing "documentation driven"

## Information

* OBS can be used as the software to screenshare and video recording

* Includes the drashland introduction? (speak to @crookse)

* Includes the sockets logo with the greenish background as the thumbnail

* Video cna be added to a "Sockets" playlist (can also be created if it doesn't exist)

* Make it chill :)

**Comment by crookse** [comment]
closing - moving this to the private task area
