### ISSUE TITLE
Error when start socket channel

### ISSUE THREAD

**Issue by arsandev** [drashland/sockets#56]
I just upgrade deno to v1.2.0 and updating all cached versions to the latest. When i start sockets again, this happened.

``[ERROR]: Property 'onMessage' does not exist on type 'SocketServer'``

also..

``[ERROR]: Expected 1 arguments, but got 2. },{`` which is related to:

```ts
const socketServer = new SocketServer();
socketServer.run({
  hostname: "localhost",
  port: 3000
},{
  reconnect: false
});
```
which previously worked.

**Comment by crookse** [comment]
Hi @arsandev,

The API changed. If you're using `onMessage()`, change it to `on()`.

When creating a socket server, use the following:

```typescript
const socketServer = new SocketServer({
  reconnect: false
});

socketServer.run({
  hostname: "localhost",
  port: 3000
});
```

Let me know how it goes.

**Comment by arsandev** [comment]
Socket server automatically runs on port 1557 with this following.

```ts
// Create the socket server
const socketServer = new SocketServer({
  reconnect: false
});
```
and
```ts
// Create "Channel 1" so that clients can send messages to it
socketServer
  .on("Channel 1", (packet: any) => {
    console.log(packet);
    console.log("Sending a message back to the client.");
    // Send messages to all clients listening to "Channel 1"
    socketServer.to(
      "Channel 1",
      `Message received! You sent "${packet.message}" as the message.`,
    );
  });
```
Now the problem is to connect from client.
I use this example.

``/index.html``
```js
import SocketClient from 'https://cdn.jsdelivr.net/gh/drashland/sockets-client@latest/client.js';
    const socketClient = new SocketClient({
      hostname: 'localhost',
      port: 1557
    });
```
I get this.
![image](https://user-images.githubusercontent.com/43356029/87907083-1a156d00-ca8e-11ea-9951-d7c38fb2be83.png)

**Comment by ebebbington** [comment]
Hey @arsandev , can you show the contents of your file that is starting the socket server? The error message you're seeing makes me think there is no socket server running, or any endpoint running on localhost:1557

**Comment by arsandev** [comment]
Nothing is running on port 1557. To be sure, I changed the port to 1234

```ts
const socketServer = new SocketServer();
socketServer.run({
  hostname: "localhost",
  port: 1234,
});
```

**Results:**
![image](https://user-images.githubusercontent.com/43356029/87956147-e14eb580-cad8-11ea-98a2-a4647079954e.png)

**Comment by ebebbington** [comment]
Hey, so you’ve got to start your socket server after instantiating it:

    socketServer.run({ hostname: “localhost”, port: 1557 })

Also that example doesn’t currently work, I made a pr earlier that actually fixed the chat example app so you can use that as a reference: https://github.com/drashland/sockets/pull/61

**Comment by arsandev** [comment]
It still doesn't work for me. all example_apps (master and v0.x branch) still don't work. I've tried making a pull request but haven't been able to solve this yet. I'm optimistic that this project can reach the stable version and I can contribute to the limits that I understand. Good job all of you!

**Comment by crookse** [comment]
Hi @arsandev ,

We're currently working towards v0.5.0 which has better documentation on building a chat app and understanding the inner workings of the framework. If you want, you can read the documentation in our staging environment right now: https://drash.land/sockets/staging
