### ISSUE TITLE
Auto-reconnect

### ISSUE THREAD

**Issue by player-4** [drashland/sockets#8]
Think about more options/config for client and server classes (i.e. redis, ping intervals, ping timeouts, path, etc)

**Comment by ebebbington** [comment]
Only stuff i can think of is the following (which is mostly what you've said):

```typescript
// pseudo code, relating to the server class
interface ServerConfigs {
  host/address?: string,
  port?: number
}
...
  private configs: ServerConfigs = {
    host/address: 'the default addr',
    port: the default port
  }

  constructor (configs: ServerConfigs) {
    if (configs.host/address) this.configs.host/address = configs....
    if (configs.port) this.configs.port = configs.port
  } 
``` 

Regarding Redis, i can only think of:
```
// pseudo code again
{
  host: string,
  port: number
  channelListeningOn: string || channelsListeningOn: string[]
  connection: any // maybe not required?
  pubSub: any = connection.pubSub
}
```

**Comment by saragee3** [comment]
Yeah, sorry a lot going on lately, but I've renamed this so it is more targeted. We need an auto-reconnect feature.  A `pingInterval ` and `pingTimeout` interval that can be set in options so we can keep the session alive.

**Comment by saragee3** [comment]
thought: we can add `ping` and `pong` to the `RESERVED_EVENT_NAMES` file
